[workspace]
resolver = "2"
members = ["pocket-device", "pocket", "pocket-user"]

#[[bin]]
#name = "pocket-device"
#path = "pocket-device/src/main.rs"
#
#[[bin]]
#name = "pocket-user"
#path = "pocket-user/src/main.rs"
