[package]
name = "pocket-device"
version = "0.60.0"
edition = "2024"
authors = ["Antonio Salsi"]
license = "GPL-3"

[features]
test_args = []

[dependencies]
pocket = { path = "../pocket" }

[[bin]]
name = "pocket-device"
path = "src/main.rs"