[package]
name = "pocket-device"
version = "0.1.0"
edition = "2021"
authors = ["Antonio Salsi"]
license = "GPL-3"

[dependencies]
pocket = { path = "../pocket" }

[[bin]]
name = "pocket-device"
path = "src/main.rs"