[package]
name = "pocket"
version = "0.1.0"
edition = "2024"
authors = ["Antonio Salsi"]
license = "GPL-3"

[dependencies]
chrono = "0.4.41"
mac_address = "1.1.8"
rusqlite = { version = "0.35.0", features = ["bundled"] }
tink-aead = "0.3.0"
hex = "0.4.3"
tink-core = "0.3.0"
