[package]
name = "pocket"
version = "0.1.0"
edition = "2024"
authors = ["Antonio Salsi"]
license = "GPL-3"

[dependencies]
chrono = "0.4.41"
cpuid = "0.1.1"
rusqlite = { version = "0.35.0", features = ["bundled"] }
