[package]
name = "pocket-user"
version = "0.60.0"
edition = "2024"
authors = ["Antonio Salsi"]
license = "GPL-3"

[dependencies]
pocket = { path = "../pocket" }

[[bin]]
name = "pocket-user"
path = "src/main.rs"